Add Quantity type
annotated-types/annotated-types pull request #65
Opened 2024-03-07 22:12 UTC by tlambert03

Adds a `Quantity` type (for discussion, see #64). 

examples:
```python
width: Annotated[float, Quantity(unit='m')] = 1
angle: Annotated[float, Quantity(unit='rad') = 0
temperature: Annotated[float, Quantity(unit='celsius')] = 100
weight: Annotated[float, Quantity(unit='kg') = 42
``` 

*annotated_types makes no attempt to parse the unit string*

2024-03-07 22:56 UTC, JelleZijlstra commented on annotated_types/__init__.py
> +    It is intended for usage with numeric types (any instance of ``numbers.Number``),
I would not mention the `numbers` module in a type checking context, there are too many problems. I think for this docstring it's fine to just say "numeric type" without precision; it's up to consumers of the library to decide exactly what to expect.

2024-03-08 08:15 UTC, Zac-HD requested changes
Thanks for including an example implementation to discuss!  It's in good shape, but we'll want to finish discussing the design over in #64 before merging 🙂

2024-03-14 00:22 UTC, tlambert03 commented
renamed to `Unit` as per general preference in #64

2024-03-24 17:41 UTC, tlambert03 commented
ok @Zac-HD @adriangb and @hgrecco. Please have a look at the added docs and readme, and let me know if you'd like anything changed

2024-04-22 00:18 UTC, tlambert03 commented
friendly ping

2024-04-22 07:43 UTC, Zac-HD approved these changes
Thanks for the ping @tlambert03 - this looks good to me, and since we've had no other objections I'm going to go ahead and merge 🙂

2024-04-22 07:44 UTC, merged